update azp for release
guoger/tape pull request #101
Opened 2020-11-15 16:12 UTC by stone-ch

Signed-off-by: Yang Cheng <chengyang418@163.com>

https://github.com/stone-ch/tape/releases. the example of release. Add a tag and then trigger the pipline(push a commit for example) it will build binary and add the assets under the release.

2020-11-16 03:05 UTC, SamYuan1990 requested changes

2020-11-16 03:05 UTC, SamYuan1990 commented on azure-pipelines.yml
> +      - script: GOOS=linux GOARCH=amd64 go build -o linux-amd64/tape ./cmd/tape && tar -czvf "tape-linux-amd64.tar.gz" linux-amd64 && GOOS=darwin GOARCH=amd64 go build -o darwin-amd64/tape ./cmd/tape
well, for build step, is good.
we did testing basing on linux.  `vmImage: 'ubuntu-latest'`
and we build binary for mac... windows.
shall we use a strategy matrix , testing(at least UT) and build in previous... which means on mac and windows that our code is non tested with platform.
ref https://docs.microsoft.com/zh-cn/azure/devops/pipelines/migrate/from-travis?view=azure-devops

2020-11-16 03:06 UTC, SamYuan1990 commented
@stone-ch , btw, why the ci check for this pr is stucked?
```
guoger.tape Expected — Waiting for status to be reported
```

2020-11-18 02:31 UTC, guoger commented
> @stone-ch , btw, why the ci check for this pr is stucked?
> 
> ```
> guoger.tape Expected — Waiting for status to be reported
> ```

https://dev.azure.com/guojiannan1101/Tape/_build/results?buildId=435&view=results
here's the error reported by azp

2020-11-18 15:58 UTC, guoger commented on azure-pipelines.yml
> +          gitHubConnection: githubServiceConnection
just invited you to Tape team on azp. I'm not exactly sure which svc connection to be added

2020-11-18 15:59 UTC, guoger commented on azure-pipelines.yml
> +      - script: GOOS=linux GOARCH=amd64 go build -o linux-amd64/tape ./cmd/tape && tar -czvf "tape-linux-amd64.tar.gz" linux-amd64 && GOOS=darwin GOARCH=amd64 go build -o darwin-amd64/tape ./cmd/tape
https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started-multiplatform?view=azure-devops

你应该是想分享这个链接吧？

2020-11-22 08:10 UTC, stone-ch commented
@guoger  It seams OK now, please add a tag to trigger the release job in pipline.

2020-11-23 15:59 UTC, closed without merging