当err为nil时，输出错误原因
guoger/tape pull request #105
Opened 2020-11-20 02:20 UTC by tianxuanhong

Signed-off-by: tianxuanhong <523713078@qq.com>

2020-11-20 15:27 UTC, guoger requested changes

2020-11-20 15:27 UTC, guoger commented on pkg/infra/proposer.go
> +					p.logger.Errorf("Err processing proposal: %s \n",r.Response)
感谢贡献

这里的case已经被原来76行覆盖了吧？即 `err == nil && (r.Response.Status < 200 || r.Reponse.Status >= 400)`

2020-11-21 01:39 UTC, tianxuanhong commented on pkg/infra/proposer.go
> +					p.logger.Errorf("Err processing proposal: %s \n",r.Response)
这个修改是因为 https://github.com/guoger/tape/issues/97 问题，我也遇到了，err为nil时，没看到错误原因。输出r.Response后类似未上传链码错误会输出："status:500 message：cannot retrieve package for chaincode mycc/v2, error open /var/hyperledger/production/chaincodes/mycc.v2: no such file or directory", 可能会帮助一些遇到类似问题的人清楚问题原因。  原来76行的代码err ==nil &&(r.Response.Status < 200 || r.Reponse.Status >= 400)这个我没注意到是在哪次修改里，最新代码好像不是。。

2020-11-21 03:21 UTC, guoger commented on pkg/infra/proposer.go
> +					p.logger.Errorf("Err processing proposal: %s \n",r.Response)
哦我知道了，这里只需要在原来的76行，把 `r.Response.Message` 也打印出来，就ok了吧？

2020-11-21 03:39 UTC, tianxuanhong commented on pkg/infra/proposer.go
> +					p.logger.Errorf("Err processing proposal: %s \n",r.Response)
嗯~~好像也行

2020-11-22 03:46 UTC, guoger commented on pkg/infra/proposer.go
> +					p.logger.Errorf("Err processing proposal: %s \n",r.Response)
@tianxuanhong 麻烦更新一下PR吧

2020-11-22 16:07 UTC, guoger approved these changes

2020-11-22 16:08 UTC, merged