update CN docs
guoger/tape pull request #115
Opened 2020-12-04 03:02 UTC by stone-ch

Signed-off-by: Yang Cheng <chengyang418@163.com>

2020-12-04 09:27 UTC, SamYuan1990 requested changes

2020-12-04 09:27 UTC, SamYuan1990 commented on docs/whatis.md
> +Tape 遵守 Apache 2.0 开源许可。
这行改了啥？

2020-12-04 09:27 UTC, SamYuan1990 commented on docs/whatis.md
> +Tape 遵守 Apache 2.0 开源许可。
如果改了，干脆链接到文件上。

2020-12-04 09:27 UTC, SamYuan1990 commented on docs/gettingstarted.md
> +    1. 编译需要Go 1.11 或者更高版本。
https://github.com/guoger/tape/blob/master/azure-pipelines.yml#L28
我们测试的是1.14吧。。。

2020-12-04 09:27 UTC, SamYuan1990 commented on docs/contribute.md
> +如果您希望贡献文档翻译，或者学习教程，也欢迎和我们联系。
https://www.bilibili.com/video/BV1k5411L79A/
学习教程 ：-）

2020-12-06 09:22 UTC, stone-ch commented on docs/gettingstarted.md
> +    1. 编译需要Go 1.11 或者更高版本。
Build from source: clone this repo and run go build ./cmd/tape at root dir. Go1.11 or higher is required.

英文版README上这么写的。

2020-12-06 09:39 UTC, SamYuan1990 commented on docs/gettingstarted.md
> +    1. 编译需要Go 1.11 或者更高版本。
我们要符合事实，而不是仅仅翻译。

2020-12-06 09:40 UTC, SamYuan1990 requested changes

2020-12-06 09:40 UTC, SamYuan1990 commented on docs/gettingstarted.md
> +我们使用 [logrus](https://github.com/sirupsen/logrus) 来管理日志，请通过环境变量 `STUPID_LOGLEVEL` 来设置日志级别。例如：
这里？

2020-12-06 13:59 UTC, guoger commented on docs/gettingstarted.md
> +    1. 编译需要Go 1.11 或者更高版本。
把这句删掉吧（英文readme里也删了），或者把测试的go版本改成1.11。我们不应该显示得要求一个比较新版本的Go

2020-12-08 03:43 UTC, stone-ch commented on docs/gettingstarted.md
> +我们使用 [logrus](https://github.com/sirupsen/logrus) 来管理日志，请通过环境变量 `STUPID_LOGLEVEL` 来设置日志级别。例如：
fixed

2020-12-08 11:31 UTC, SamYuan1990 commented
please update to latest master. squash, and update in EN document.
remove go version?

2020-12-08 14:58 UTC, stone-ch commented
see #120

2020-12-08 14:58 UTC, closed without merging