add version subcommand
guoger/tape pull request #126
Opened 2020-12-12 14:00 UTC by hellosmallstone

The version info is a const value, which is set manually when tape is released.
And integration test will check the version info, which must be consistent with the const value.

This is the second modification to fix #113 .

```
./tape version
tape:
 Version: 0.0.2
```

Signed-off-by: wuxu <wuxu1103@163.com>

2020-12-14 05:34 UTC, guoger requested changes
i think this could be more verbose, i.e. here's what `docker version` prints:
```
➜  ~ docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

2020-12-15 12:14 UTC, hellosmallstone commented
@guoger I added Version, Go version and  OS/Arch info in the new commit. But commit hash and Built info need to be dynamically obtained at compile time by `go build -ldflags`. I suggest adding a makefile file to achieve unified compilation to set the infos, which is not a small change for the whole project and may be fixed in a new issue.

2020-12-15 12:26 UTC, guoger requested changes
I'm ok with incremental change and merge as is. Just added some comments for minor fix. If you want to address them in next PR, i'm also fine with it. Just let me know

2020-12-15 12:26 UTC, guoger commented on e2e/e2e_test.go
> +				Eventually(tapeSession.Out).Should(Say("tape:\n Version: 0.0.2"))
this should `say` GoVersion and more, right?

2020-12-15 12:26 UTC, guoger commented on pkg/infra/version.go
> +	versionInfo = "0.0.2"
`versionInfo` -> `version`

2020-12-15 12:26 UTC, guoger commented on cmd/tape/main.go
> +		fmt.Println(infra.GetVersionInfo())
return value already has `\n`, so you don't need to `println`

2020-12-16 11:47 UTC, guoger approved these changes

2020-12-16 11:48 UTC, merged